query ProjectCardsQuery($repositoryId: ID!) {
  node(id: $repositoryId) {
    ... on Repository {
      owner {
        url
        # Projects can be attached to an Organization...
        ... on Organization {
          projects(first: 10, states: [OPEN]) {
            nodes {
              ...ProjectCardsFragment
            }
          }
        }
      }
      # ... or on a Repository for User
      projects(first: 10, states: [OPEN]) {
        nodes {
          ...ProjectCardsFragment
        }
      }
    }
  }
}

fragment ProjectCardsFragment on ProjectCardsQuery {
  name
  id
  columns(first: 50) {
    totalCount
    nodes {
      id
      url
      lastCards: cards(last: 1, archivedStates: NOT_ARCHIVED) {
        totalCount
        nodes {
          url
          id
          note
        }
      }
    }
  }
}
